services:
  mooc-mysql:
    extends:
      file: mysql.yml
      service: mooc-mysql
    networks:
      mooc-net:
        aliases:
          - MASTER_DB_SERVER
          - SLAVE_DB_SERVER_1
          - SLAVE_DB_SERVER_2
        ipv4_address: 172.25.0.2
  mooc-redis:
    extends:
      file: redis.yml
      service: mooc-redis
    networks:
      mooc-net:
        aliases:
          - REDIS_SERVER
        ipv4_address: 172.25.0.3
  # mooc-monitor:
  #   extends:
  #     file: monitor.yml
  #     service: mooc-monitor
  #   networks:
  #     mooc-net:
  #       aliases:
  #         - MONITOR_SERVER
  #       ipv4_address: 172.25.0.4
networks:
    mooc-net:
      #name: mooc-net
      ipam:
        config:
          - subnet: 172.25.0.0/16
            gateway: 172.25.0.1
