version: '2'
services:
    mooc-mysql:
        image: mysql:8.0
        volumes:
            - ./data/mysql/conf:/etc/mysql/conf.d
            - ./data/mysql/data:/var/lib/mysql
            - ../sql/mooc.sql:/docker-entrypoint-initdb.d/mooc.sql
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=mooc
            - LANG=C.UTF-8
        ports:
            - 3306:3306
        command: mysqld  --skip-ssl --character_set_server=utf8mb4 --sql_mode=""